Feature/fixing box automaton (Reup PR#137)
UnitexGramLab/gramlab-ide pull request #150
Opened 2020-07-10 09:22 UTC by FLambertD

## Description
This is an update of the open PR[#137](https://github.com/UnitexGramLab/gramlab-ide/pull/137).
Add the functionality of adding boxes in an automaton. When we add new boxes in the automaton it must be coherent with old boxes. Now the program can create boxes and verify if it's coherent.

This PR is associated with the PR [#144](https://github.com/UnitexGramLab/gramlab-ide/pull/144).

## Motivation and Context
Before, we only could change the automaton with removing or changing boxes but now we couldn't add new boxes.

## How Has This Been Tested?
For tests we create new boxes in the automaton and we check if new boxes are created or not.
It has been tested with a lot of basics graphs and for specific tests we use the next graph :
[essais-editeur-treillis_snt.zip](https://github.com/UnitexGramLab/gramlab-ide/files/3645833/essais-editeur-treillis_snt.zip)

## Type of files

- [ ] `bin`: Binary files
- [ ] `ci`: Continuous integration files
- [ ] `doc`: Documentation files
- [x] Plain-text source code files

## Level of change

- [ ] `break`: Breaking change
- [ ] `exp`: Experimental change
- [ ] `tmp`: Temporal change
- [ ] `major`: Major change
- [x] `minor`: Minor change
- [ ] `sec`: Vulnerability-related change
- [ ] None of the above (normal change)

## Type of change

- [ ] `deprecat`: Deprecation of a once-stable feature
- [ ] `enhance`: Enhancement in existing functionality
- [ ] `fix`: Bug fix
- [x] `feature`: New feature
- [ ] `hotfix`: Hotfix for bugs
- [ ] `refactor`: Improve coding style, comments
- [ ] `remove`: Remove a feature

## Checklist:

- [x] My code compiles
- [x] My code follows the code style of this project
- [x] My code includes javadoc/doxygen where appropriate
- [x] My code is well factored, so that there is not repetitive code in the wild
- [x] My code does not require a change in the documentation, if so I already opened an issue to list the changes
- [x] I have read the **CONTRIBUTING** document
- [x] I have read the **Commit Message Guidelines**
- [x] I understand that all commits on my pull request will be squashed to a single good one

2020-07-29 16:25 UTC, martinec commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingState.java
> +	TO_CHECK,
This variable must be documented

2020-09-11 08:33 UTC, eric-laporte requested changes
Thanks for involving yourself in other developers' code. A few parts require reflection.

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				lstRemove.add(allPaths.get(tmp));
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			allPaths.remove(lstRemove.get(i));
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +					setBoxStateInternal(sortedNodes[arrayList.get(i)], TaggingState.TO_CHECK);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			allPaths.add(currentPath);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			lstContext.add(new Context(arrayList));
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						c.currentBox--;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				finalState = i1;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			dst[i] = TaggingState.NEUTRAL;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +							newBegin = boxes[sortedNodes[lst.get(i-1)]].getBounds().getEnd_in_tokens() + tmp;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +							newBegin = boxes[sortedNodes[lst.get(i-1)]].getBounds().getStart_in_tokens();
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						boxes[sortedNodes[lst.get(i)]].getBounds().setStart_in_tokens(newBegin);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				last += 2;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +					hasSpace = true;
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						ctxtRemove.add(context);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			copyContext.remove(context);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				sb.append(boxes[num_box].getContentText());
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			sb.append(boxes[num_box].getContentText());
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			return box.getContent().split(",")[0].substring(1);
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
>  			taggingStates[i] = TaggingState.NEUTRAL;
this overwrites user's hand-marking of preferred boxes!

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * for each box we will start at it's starting bound, split the inside based on delimiters and add them to the hashmap.
it's --> its

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * if 2 words split by a comma are found, they will be stored subsequently in the hashmap at the starting bound's value, then +1 and so on.
The description in this line is wrong and is about a detail which is not so relevant

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			if( gb.getContent().contains("{")  )
call `getTextBoxe(gb)` or `gb.getContentText()` instead of these 5 lines

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +                        if( gb.getBounds().getEnd_in_tokens()
indent less

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			== gb.getBounds().getStart_in_tokens() + tokensList.size() - 1) {
indent more

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +		    for( String s : tokensList ) {
indent more

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/**  This function creates all the paths we can have between the first box
add what this method does, I think it is, marking as TO_CHECK the USELESS boxes between bfp and bfs that have become accessible and co-accessible

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 *  paths which contains at least a box which is tagged USELESS
'which contains' --> 'that contain'

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * 			The number of the first box in the path
mention that `bfp` and `bfs` are factorization nodes

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				if(taggingStates[sortedNodes[arrayList.get(i)]] != TaggingState.NEUTRAL
maybe it is equivalent and quicker to test if box is `USELESS`?

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * This function checks if the at least one box of the boxes in arrayList
the at least --> at least

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * 			ArrayList of the number of each boxes of the path
each boxes --> each box

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/** This function creates all paths between the first box bfp and the last box bfs
rename first two parameters as `fb1` and `fb2` for instance, and mention they are factorization nodes

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * @param current
current --> currentPath

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/** This function checks if the new branch can be add to the automaton or not
add --> added
also, mention this method marks as `TO_CHECK` the `USELESS` boxes that have become accessible and co-accessible

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * If it's not, we remove the last transition in the automaton
it's not --> it can't

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +		findString(boxes[sortedNodes[renumber[prev]]], boxes[sortedNodes[renumber[next]]], new StringBuilder(), boxes[sortedNodes[renumber[prev]]], new StringBuilder());
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			taggingStates[i1] = TaggingState.NEUTRAL;
overwrites the user's hand-marking of preferred states!

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	private void copyStates(TaggingState[] src, TaggingState[] dst) {
This method does not use first parameter and does not copy; calls to this method suggest the expected behaviour of the method is to copy first parameter into second parameter

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						boxes[sortedNodes[lst.get(i)]].getBounds().setEnd_in_tokens(findLastToken(boxes[sortedNodes[lst.get(i)]], copyContext));
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						boxes[sortedNodes[lst.get(i)]].getBounds().setEnd_in_tokens(findLastToken(boxes[sortedNodes[lst.get(i)]], copyContext));
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +					sb.append(s.charAt(s.length()-1));
Binary operator `-` should be separated from its operands by spaces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						boxes[sortedNodes[lst.get(i)]].getBounds().setEnd_in_letters(cpt-1);
Binary operator `-` should be separated from its operands by spaces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				if(context.currentBox < context.path.size() && boxes[sortedNodes[context.path.get(context.currentBox)]].equals(boxes[bfs])) {
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * Find the sentence of the new path and return it
sentence --> text

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				sb.append(" ");
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				sb.append(getTextBoxe(boxes[sortedNodes[in]]));
insert braces

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * This function finds the last coordinated of each previous boxes of boxes in lstContext
`last coordinated` --> `end coordinate`, `coordinated` --> `coordinate`, `each previous boxes` --> `each direct predecessor`

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				return boxes[sortedNodes[context.path.get(context.currentBox - 1)]].getBounds().getEnd_in_tokens();
it seems this instruction returns the end-coordinate of a direct predecessor of the current box, whereas the doc tells the method returns the end-coordinate of the current box; calls to this method suggest the expected behaviour of the method is the one described in the doc

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * This function finds the first coordinated of one of the next box of the current one
coordinated --> coordinate, of (one of) the next box --> of a direct successor

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * This function finds the first coordinated of boxes which are in lstContext
coordinated --> coordinate

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * @return the first coordinated of the current box
doc is misleading, the method returns a distance between two coordinates

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +						if(context.currentBox + 1 < context.path.size() && boxes[sortedNodes[context.path.get(context.currentBox+1)]].type != GenericGraphBox.FINAL
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * This function is used to find all sentences between the 2 factorizations box
sentence --> sequence, factorization(s) box --> factorization node, the number of boxes of --> the number of each box in

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/* Return the text contains in the box */
contains in --> contained in

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/* Diplay all sentences in lstTok and their path in lstPath */
insert "useful only in case of debugging"

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +			if(taggingStates[i] != TaggingState.USELESS)
`factorization[i] = (taggingStates[i] != TaggingState.USELESS)`

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +				if (srcBox.transitions.contains(destBox) && (destBox.hasOutgoingTransitions || destBox.type == GenericGraphBox.FINAL)) {
split long line

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	 * USELESS if they're neither of those.
neither of those --> not both

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +					 * set its state to [NOT_PREFERRED] TO_CHECK as in to be checked
"to [NOT_PREFERRED] TO_CHECK as in to be checked" --> "to TO_CHECK"

2020-09-11 08:33 UTC, eric-laporte commented on unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java
> +	/*public void updateBoundsDiffToken(ArrayList<GenericGraphBox> selectedBoxes, TfstGraphBox b) {
outdated code

2021-08-09 12:53 UTC, merged