feature/CasysAndPreprocess
UnitexGramLab/gramlab-ide pull request #155
Opened 2021-08-30 13:38 UTC by Sandy-CHERY

## Description

Fixes 1 Change Cassys to solve the max stack size reached problem #

## Motivation and Context

Alexis Neme have a problem :
"When I execute Cassys  command (below) with IDE it generates the error "Max stack size reached" (attcahed file)
"Local\Unitex\App\UnitexToolLogger.exe" Cassys "-aUnitex3_2\English\Alphabet.txt" "-tUnitex3_2\English\Corpus\text.snt" "-lUnitex3_2\English\CasSys\cascade.csc" -v "-rUnitex3_2\English\Graphs\" "--input_offsets=Unitex3_2\English\Corpus\text_snt\normalize.out.offsets" -qutf8-no-bom

When I execute Cassys  command (below) with a command line, it does generate an error
"Local\Unitex\App\UnitexToolLogger.exe" Cassys "-aUnitex3_2\English\Alphabet.txt" "-tUnitex3_2\English\Corpus\text.snt" "-lUnitex3_2\English\CasSys\cascade.csc" -v "-rUnitex3_2\English\Graphs\" "--input_offsets=Unitex3_2\English\Corpus\text_snt\normalize.out.offsets" -qutf8-no-bom --locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000

I propose to include these parameters in bold to the Cassys command line call from the IDE"

## What I did

In gramlab-ide\unitex\src\fr\umlv\unitex\process\commands\CommandBuilder.java,
when we create the Cassys comand "-qutf8-no-bom", I add "-qutf8-no-bom --locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000"

Fixes 2 Preprocessing#

## Motivation and Context

When you lanch the Preprocessing, graph in MERGE mode and graph in REPLACE mode have the same path (Graphs\Preprocessing\Replace)

## What I did

In gramlab-ide\unitex\src\fr\umlv\unitex\frames\PreprocessDialog.java
Sentence and Replace used the same variable, I creat two different variables for having two different paths (Graphs\Preprocessing\Sentence and Graphs\Preprocessing\Replace).

2021-09-09 10:38 UTC, martinec commented on XAlignConfigFrame.java
> + * Copyright (C) 2001-2019 Université Paris-Est Marne-la-Vallée <unitex@univ-mlv.fr>
2001-**2021**

2021-09-09 10:40 UTC, martinec commented on XAlignConfigFrame.java
> +							"Your source file is a .txt one. Please select the\n"
What about:

```
Your source file is in .txt format. 
Please select the destination file that will be used by XAlign (TEI format).
```

2021-09-09 11:29 UTC, martinec requested changes
It seems that the files in your PR have been modified and then placed in the wrong place.

At this point, it is not possible to compile the code, nor to visualize the changes made.

Please update your PR or send a new one with the necessary adjustments.

2021-09-09 11:29 UTC, martinec commented on PreprocessDialog.java
> +/*
It seems that this file is already under `unitex/src/en/umlv/unitex/frames/PreprocessDialog.java` is there any reason to try to create a new copy under the root?

2021-09-09 11:29 UTC, martinec commented on XAlignConfigFrame.java
> +/*
It seems that this file is already under `unitex/src/fr/umlv/unitex/frames/XAlignConfigFrame.java` is there any reason to try to create a new copy under the root?

2021-09-09 11:29 UTC, martinec commented on config/Config.java
> +/*
It seems that this file is already under `unitex/src/fr/umlv/unitex/config/Config.java`  is there any reason to try to create a new copy under `config/Config.java`?

2021-09-09 11:29 UTC, martinec commented on process/commands/AbstractCommand.java
> +/*
It seems that this file is already under `/unitex/src/fr/umlv/unitex/process/commands/AbstractCommand.java` is there any reason to try to create a new copy under `process/commands/AbstractCommand.java`?

2021-09-09 11:29 UTC, martinec commented on process/commands/CommandBuilder.java
> +/*
It seems that this file is already under `unitex/src/fr/umlv/unitex/process/commands/CommandBuilder.java` is there any reason to try to create a new copy under `process/commands/CommandBuilder.java`?

2021-09-09 13:43 UTC, Sandy-CHERY commented
Bonjour,
Peux-tu m'aider, je ne parviens pas a mettre a jour la PR.
Est-ce que je dois la fermer et en refaire une ?

2021-09-10 07:03 UTC, martinec commented
> It seems that the files in your PR have been modified and then placed in the wrong place.
> 
> At this point, it is not possible to compile the code, nor to visualize the changes made.
> 
> Please update your PR or send a new one with the necessary adjustments.

As stated before, for this specific PR, if you wish, you can close it and create a new one.

2021-09-10 08:59 UTC, closed without merging